name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: build-with-dotnet
      run: |
        dotnet build Either/Either.sln --configuration Release

    - name: unit-tests
      run: |
        dotnet test Either/Either.sln --configuration Release

    - name: package-library
      run: |
        dotnet pack Either/Either.sln
        
    - name: publish-library
      run: |
        dotnet nuget push Either/Either/bin/Debug/ControlFlow.Type.Either.1.0.0.nupkg -k oy2it4gac2yrr5z76cxa577f4vctf3lubkkrphvsad47zy -s https://api.nuget.org/v3/index.json