name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 'netcore3.0'
    - name: unit-tests
      run: |
        cd '../../\Either\\EitherTests\\EitherTests.csproj'
        dotnet test
    - name: package-&-publish-library
      run: |
        cd '../../\Either\\Either\\Either.csproj'
        dotnet pack
        dotnet nuget push Either.1.0.0.nupkg -k oy2dzacin3ajjbsj7kha446mq57mgbre3ejajvgdep2uau -s https://api.nuget.org/v3/index.json