name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: build-with-dotnet
      run: |
        dotnet build Either/Either.sln --configuration Release

    - name: unit-tests
      run: |
        dotnet test Either/Either.sln --configuration Release

    - name: package-library
      run: |
        dotnet pack Either/Either.sln
        
    - name: publish-library
      run: |
        dotnet nuget push Either/Either/bin/Debug/ControlFlow.Type.Either.1.0.1.nupkg -k {{.nuget.apiKey | base64 -D}} -s https://api.nuget.org/v3/index.json


nuget:
  apiKey: b3kyZXR5em41bDQ2dndhbWpsZmFqNDJ6cXRjY2h0MmUzZmJ6amdwZ3BiaTR5NA==