name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: build-with-dotnet
      run: |
        cd '../../Either/Either'
        dotnet build Either.csproj --configuration Release
    - name: unit-tests
      run: |
        cd '../../Either/EitherTests'
        dotnet test 'EitherTests.csproj' --configuration Release
    - name: package-library
      run: |
        cd '../../Either/Either'
        dotnet pack 'Either.csproj' --configuration Release
    - name: publish-library
      run: |
        cd '../../Either/Either'
        dotnet nuget push Either.1.0.0.nupkg -k oy2dzacin3ajjbsj7kha446mq57mgbre3ejajvgdep2uau -s https://api.nuget.org/v3/index.json --configuration Release